steps:

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy with commit version without promote'
  args:
  - 'app'
  - 'deploy'
  - '--quiet'
  - '$_DEPLOY_FILE'
  - '--bucket'
  - '$_BUCKET'
  - '--no-promote'
  - '$_GAE_PROMOTE'
  - '-v'
  - '$_GAE_VERSION-$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy with environment version without promote'
  args:
  - 'app'
  - 'deploy'
  - '--quiet'
  - '$_DEPLOY_FILE'
  - '--bucket'
  - '$_BUCKET'
  - '--no-promote'
  - '$_GAE_PROMOTE'
  - '-v'
  - '$_GAE_VERSION'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Set Traffic 100% for environment version'
  args:
  - 'app'
  - 'services'
  - 'set-traffic'
  - '$_SERVICE_NAME'
  - '--splits'
  - '$_GAE_TRAFFIC'
  - '-q'
