steps:

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy App'
  args:
  - 'app'
  - 'deploy'
  - '--project'
  - '$PROJECT_ID'
  - '-q'
  - '$_GAE_PROMOTE'
  - '-v'
  - '$_GAE_VERSION'
  timeout: '1600s'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Traffic Service'
  args:
  - 'app'
  - 'services'
  - '--project'
  - '$PROJECT_ID'
  - 'set-traffic'
  - '--splits'
  - '$_GAE_TRAFFIC'
