steps:

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy App'
  args:
  - 'app'
  - 'deploy'
  - '$_DEPLOY_FILE'
  - '--bucket'
  - '$_BUCKET'
  - '--project'
  - '$PROJECT_ID'
  - '-q'
  - '$_GAE_PROMOTE'
  - '-v'
  - '$_GAE_VERSION'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'app'
  - 'services'
  - '--project'
  - '$PROJECT_ID'
  - 'set-traffic'
  - '--splits'
  - '$_GAE_TRAFFIC'
