steps:

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy App'
  args:
  - 'app'
  - 'deploy'
  - '$_DEPLOY_FILE'
  - '--bucket'
  - '$_BUCKET'
  - '-q'
  - '$_GAE_PROMOTE'
  - '-v'
  - '$_GAE_VERSION'
