steps:

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy with tag version'
  args:
  - 'app'
  - 'deploy'
  - '--quiet'
  - '$_DEPLOY_FILE'
  - '--bucket'
  - '$_BUCKET'
  - '$_GAE_PROMOTE'
  - '-v'
  - '$TAG_NAME'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy with dev version'
  args:
  - 'app'
  - 'deploy'
  - '--quiet'
  - '$_DEPLOY_FILE'
  - '--bucket'
  - '$_BUCKET'
  - '$_GAE_PROMOTE'
  - '-v'
  - '$_GAE_VERSION'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Set Traffic 100% for production version'
  args:
  - 'app'
  - 'services'
  - 'set-traffic'
  - '$_SERVICE_NAME'
  - '--splits'
  - '$_GAE_TRAFFIC'
  - '-q'
