steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'app'
  - 'deploy'
  - '--quiet'
  - 'key'
  - '$_KEY'
  # - '$_DEPLOY_FILE'
  # - '--bucket'
  # - '$_BUCKET'
  # - '$_GAE_PROMOTE'
  # - '-v'
  # - '$_GAE_VERSION'

# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - 'app'
#   - 'services'
#   - '--project'
#   - '$PROJECT_ID'
#   - 'set-traffic'
#   - '--splits'
#   - '$_GAE_TRAFFIC'
