steps:

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy To App Engine'
  args:
  - 'app'
  - 'deploy'
  - '--quiet'
  - '$_DEPLOY_FILE'
  - '--bucket'
  - '$_BUCKET'
  - '$_GAE_PROMOTE'
  - '-v'
  - '$_GAE_VERSION'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Set Traffic 100% for production version'
  args:
  - 'app'
  - 'services'
  - '$_SERVICE_NAME'
  - 'set-traffic'
  - '--splits'
  - '$_GAE_TRAFFIC'
