steps:

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy with commit version without promote'
  args:
  - 'app'
  - 'deploy'
  - '--quiet'
  - '$_DEPLOY_FILE'
  - '--bucket'
  - '$_BUCKET'
  - '$_GAE_PROMOTE'
  - '-v'
  - '$_GAE_VERSION-$SHORT_SHA'
  - '--no-promote'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy with environment version without promote'
  args:
  - 'app'
  - 'deploy'
  - '--quiet'
  - '$_DEPLOY_FILE'
  - '--bucket'
  - '$_BUCKET'
  - '$_GAE_PROMOTE'
  - '-v'
  - '$_GAE_VERSION'
  - '--no-promot'

- name: 'ubuntu'
  id: 'Set delay time to wait new version ready'
  args: ['sleep', '60']
  timeout: 100s

- name: 'ubuntu'
  id: 'Test set delay time'
  args: ['echo', 'hello world, after 60s']

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Set Traffic 100% for environment version'
  args:
  - 'app'
  - 'services'
  - 'set-traffic'
  - '$_SERVICE_NAME'
  - '--splits'
  - '$_GAE_TRAFFIC'
  - '-q'
