service: dev-webapp
runtime: nodejs10
env: standard

instance_class: F2
automatic_scaling:
  min_idle_instances: 5
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

# featureSettings:
#   splitHealthChecks: true

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

